CREATE DATABASE impact;
GRANT ALL PRIVILEGES ON DATABASE impact TO build;

CREATE DATABASE impactscore;
GRANT ALL PRIVILEGES ON DATABASE impactscore TO build;

CREATE DATABASE zendantennes;
GRANT ALL PRIVILEGES ON DATABASE zendantennes TO build;
